name: Branch testing pipeline

on:
  push:
    branches-ignore:
      - main

jobs:
  tests_run_on_branch:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run:  npm run build
      - name: test with jest
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run cypress
          start: node server.js
          wait-on: http://localhost:3001